/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq.tables;


import com.gmo.big2.store.mysql.schema.jooq.BigTwo;
import com.gmo.big2.store.mysql.schema.jooq.Indexes;
import com.gmo.big2.store.mysql.schema.jooq.Keys;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.PlayerScoreRecord;
import com.gmo.big2.store.mysql.support.UUIDBinaryConverter;

import java.util.Arrays;
import java.util.List;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerScore extends TableImpl<PlayerScoreRecord> {

    private static final long serialVersionUID = 1262815839;

    /**
     * The reference instance of <code>big_two.player_score</code>
     */
    public static final PlayerScore PLAYER_SCORE = new PlayerScore();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<PlayerScoreRecord> getRecordType() {
        return PlayerScoreRecord.class;
    }

    /**
     * The column <code>big_two.player_score.player_uuid</code>.
     */
    public final TableField<PlayerScoreRecord, UUID> PLAYER_UUID = createField("player_uuid", org.jooq.impl.SQLDataType.BINARY(16).nullable(false), this, "", new UUIDBinaryConverter());

    /**
     * The column <code>big_two.player_score.score</code>.
     */
    public final TableField<PlayerScoreRecord, Integer> SCORE = createField("score", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaultValue(org.jooq.impl.DSL.inline("0", org.jooq.impl.SQLDataType.INTEGER)), this, "");

    /**
     * Create a <code>big_two.player_score</code> table reference
     */
    public PlayerScore() {
        this(DSL.name("player_score"), null);
    }

    /**
     * Create an aliased <code>big_two.player_score</code> table reference
     */
    public PlayerScore(String alias) {
        this(DSL.name(alias), PLAYER_SCORE);
    }

    /**
     * Create an aliased <code>big_two.player_score</code> table reference
     */
    public PlayerScore(Name alias) {
        this(alias, PLAYER_SCORE);
    }

    private PlayerScore(Name alias, Table<PlayerScoreRecord> aliased) {
        this(alias, aliased, null);
    }

    private PlayerScore(Name alias, Table<PlayerScoreRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return BigTwo.BIG_TWO;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.PLAYER_SCORE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<PlayerScoreRecord> getPrimaryKey() {
        return Keys.KEY_PLAYER_SCORE_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<PlayerScoreRecord>> getKeys() {
        return Arrays.<UniqueKey<PlayerScoreRecord>>asList(Keys.KEY_PLAYER_SCORE_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<PlayerScoreRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<PlayerScoreRecord, ?>>asList(Keys.PLAYER_SCORE_PLAYER_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerScore as(String alias) {
        return new PlayerScore(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerScore as(Name alias) {
        return new PlayerScore(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerScore rename(String name) {
        return new PlayerScore(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public PlayerScore rename(Name name) {
        return new PlayerScore(name, null);
    }
}
