/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq;


import com.gmo.big2.store.mysql.schema.jooq.tables.Game;
import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayer;
import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayerGroup;
import com.gmo.big2.store.mysql.schema.jooq.tables.Player;
import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerGroup;
import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerScore;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>big_two</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index GAME_PRIMARY = Indexes0.GAME_PRIMARY;
    public static final Index GAME_PLAYER_GAME_PLAYER_PLAYER_FK = Indexes0.GAME_PLAYER_GAME_PLAYER_PLAYER_FK;
    public static final Index GAME_PLAYER_PRIMARY = Indexes0.GAME_PLAYER_PRIMARY;
    public static final Index GAME_PLAYER_GROUP_GAME_PLAYER_GROUP_PLAYER_GROUP_FK = Indexes0.GAME_PLAYER_GROUP_GAME_PLAYER_GROUP_PLAYER_GROUP_FK;
    public static final Index GAME_PLAYER_GROUP_PRIMARY = Indexes0.GAME_PLAYER_GROUP_PRIMARY;
    public static final Index PLAYER_DISPLAY_NAME = Indexes0.PLAYER_DISPLAY_NAME;
    public static final Index PLAYER_EMAIL_ADDRESS = Indexes0.PLAYER_EMAIL_ADDRESS;
    public static final Index PLAYER_PRIMARY = Indexes0.PLAYER_PRIMARY;
    public static final Index PLAYER_GROUP_PLAYER_GROUP_PLAYER1_FK = Indexes0.PLAYER_GROUP_PLAYER_GROUP_PLAYER1_FK;
    public static final Index PLAYER_GROUP_PLAYER_GROUP_PLAYER2_FK = Indexes0.PLAYER_GROUP_PLAYER_GROUP_PLAYER2_FK;
    public static final Index PLAYER_GROUP_PLAYER_GROUP_PLAYER3_FK = Indexes0.PLAYER_GROUP_PLAYER_GROUP_PLAYER3_FK;
    public static final Index PLAYER_GROUP_PLAYER_GROUP_PLAYER4_FK = Indexes0.PLAYER_GROUP_PLAYER_GROUP_PLAYER4_FK;
    public static final Index PLAYER_GROUP_PRIMARY = Indexes0.PLAYER_GROUP_PRIMARY;
    public static final Index PLAYER_SCORE_PRIMARY = Indexes0.PLAYER_SCORE_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index GAME_PRIMARY = Internal.createIndex("PRIMARY", Game.GAME, new OrderField[] { Game.GAME.GAME_UUID }, true);
        public static Index GAME_PLAYER_GAME_PLAYER_PLAYER_FK = Internal.createIndex("game_player_player_fk", GamePlayer.GAME_PLAYER, new OrderField[] { GamePlayer.GAME_PLAYER.PLAYER_UUID }, false);
        public static Index GAME_PLAYER_PRIMARY = Internal.createIndex("PRIMARY", GamePlayer.GAME_PLAYER, new OrderField[] { GamePlayer.GAME_PLAYER.GAME_UUID, GamePlayer.GAME_PLAYER.PLAYER_UUID }, true);
        public static Index GAME_PLAYER_GROUP_GAME_PLAYER_GROUP_PLAYER_GROUP_FK = Internal.createIndex("game_player_group_player_group_fk", GamePlayerGroup.GAME_PLAYER_GROUP, new OrderField[] { GamePlayerGroup.GAME_PLAYER_GROUP.PLAYER_GROUP_UUID }, false);
        public static Index GAME_PLAYER_GROUP_PRIMARY = Internal.createIndex("PRIMARY", GamePlayerGroup.GAME_PLAYER_GROUP, new OrderField[] { GamePlayerGroup.GAME_PLAYER_GROUP.GAME_UUID, GamePlayerGroup.GAME_PLAYER_GROUP.PLAYER_GROUP_UUID }, true);
        public static Index PLAYER_DISPLAY_NAME = Internal.createIndex("display_name", Player.PLAYER, new OrderField[] { Player.PLAYER.DISPLAY_NAME }, true);
        public static Index PLAYER_EMAIL_ADDRESS = Internal.createIndex("email_address", Player.PLAYER, new OrderField[] { Player.PLAYER.EMAIL_ADDRESS }, true);
        public static Index PLAYER_PRIMARY = Internal.createIndex("PRIMARY", Player.PLAYER, new OrderField[] { Player.PLAYER.PLAYER_UUID }, true);
        public static Index PLAYER_GROUP_PLAYER_GROUP_PLAYER1_FK = Internal.createIndex("player_group_player1_fk", PlayerGroup.PLAYER_GROUP, new OrderField[] { PlayerGroup.PLAYER_GROUP.PLAYER_UUID_1 }, false);
        public static Index PLAYER_GROUP_PLAYER_GROUP_PLAYER2_FK = Internal.createIndex("player_group_player2_fk", PlayerGroup.PLAYER_GROUP, new OrderField[] { PlayerGroup.PLAYER_GROUP.PLAYER_UUID_2 }, false);
        public static Index PLAYER_GROUP_PLAYER_GROUP_PLAYER3_FK = Internal.createIndex("player_group_player3_fk", PlayerGroup.PLAYER_GROUP, new OrderField[] { PlayerGroup.PLAYER_GROUP.PLAYER_UUID_3 }, false);
        public static Index PLAYER_GROUP_PLAYER_GROUP_PLAYER4_FK = Internal.createIndex("player_group_player4_fk", PlayerGroup.PLAYER_GROUP, new OrderField[] { PlayerGroup.PLAYER_GROUP.PLAYER_UUID_4 }, false);
        public static Index PLAYER_GROUP_PRIMARY = Internal.createIndex("PRIMARY", PlayerGroup.PLAYER_GROUP, new OrderField[] { PlayerGroup.PLAYER_GROUP.PLAYER_GROUP_UUID }, true);
        public static Index PLAYER_SCORE_PRIMARY = Internal.createIndex("PRIMARY", PlayerScore.PLAYER_SCORE, new OrderField[] { PlayerScore.PLAYER_SCORE.PLAYER_UUID }, true);
    }
}
