/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq;


import com.gmo.big2.store.mysql.schema.jooq.tables.Game;
import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayer;
import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayerGroup;
import com.gmo.big2.store.mysql.schema.jooq.tables.Player;
import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerGroup;
import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerScore;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.GamePlayerGroupRecord;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.GamePlayerRecord;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.GameRecord;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.PlayerGroupRecord;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.PlayerRecord;
import com.gmo.big2.store.mysql.schema.jooq.tables.records.PlayerScoreRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>big_two</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<GameRecord> KEY_GAME_PRIMARY = UniqueKeys0.KEY_GAME_PRIMARY;
    public static final UniqueKey<GamePlayerRecord> KEY_GAME_PLAYER_PRIMARY = UniqueKeys0.KEY_GAME_PLAYER_PRIMARY;
    public static final UniqueKey<GamePlayerGroupRecord> KEY_GAME_PLAYER_GROUP_PRIMARY = UniqueKeys0.KEY_GAME_PLAYER_GROUP_PRIMARY;
    public static final UniqueKey<PlayerRecord> KEY_PLAYER_PRIMARY = UniqueKeys0.KEY_PLAYER_PRIMARY;
    public static final UniqueKey<PlayerRecord> KEY_PLAYER_EMAIL_ADDRESS = UniqueKeys0.KEY_PLAYER_EMAIL_ADDRESS;
    public static final UniqueKey<PlayerRecord> KEY_PLAYER_DISPLAY_NAME = UniqueKeys0.KEY_PLAYER_DISPLAY_NAME;
    public static final UniqueKey<PlayerGroupRecord> KEY_PLAYER_GROUP_PRIMARY = UniqueKeys0.KEY_PLAYER_GROUP_PRIMARY;
    public static final UniqueKey<PlayerScoreRecord> KEY_PLAYER_SCORE_PRIMARY = UniqueKeys0.KEY_PLAYER_SCORE_PRIMARY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<GameRecord, PlayerRecord> GAME_PLAYER_FK = ForeignKeys0.GAME_PLAYER_FK;
    public static final ForeignKey<GamePlayerRecord, GameRecord> GAME_PLAYER_GAME_FK = ForeignKeys0.GAME_PLAYER_GAME_FK;
    public static final ForeignKey<GamePlayerRecord, PlayerRecord> GAME_PLAYER_PLAYER_FK = ForeignKeys0.GAME_PLAYER_PLAYER_FK;
    public static final ForeignKey<GamePlayerGroupRecord, GameRecord> GAME_PLAYER_GROUP_GAME_FK = ForeignKeys0.GAME_PLAYER_GROUP_GAME_FK;
    public static final ForeignKey<GamePlayerGroupRecord, PlayerGroupRecord> GAME_PLAYER_GROUP_PLAYER_GROUP_FK = ForeignKeys0.GAME_PLAYER_GROUP_PLAYER_GROUP_FK;
    public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER1_FK = ForeignKeys0.PLAYER_GROUP_PLAYER1_FK;
    public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER2_FK = ForeignKeys0.PLAYER_GROUP_PLAYER2_FK;
    public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER3_FK = ForeignKeys0.PLAYER_GROUP_PLAYER3_FK;
    public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER4_FK = ForeignKeys0.PLAYER_GROUP_PLAYER4_FK;
    public static final ForeignKey<PlayerScoreRecord, PlayerRecord> PLAYER_SCORE_PLAYER_FK = ForeignKeys0.PLAYER_SCORE_PLAYER_FK;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<GameRecord> KEY_GAME_PRIMARY = Internal.createUniqueKey(Game.GAME, "KEY_game_PRIMARY", Game.GAME.GAME_UUID);
        public static final UniqueKey<GamePlayerRecord> KEY_GAME_PLAYER_PRIMARY = Internal.createUniqueKey(GamePlayer.GAME_PLAYER, "KEY_game_player_PRIMARY", GamePlayer.GAME_PLAYER.GAME_UUID, GamePlayer.GAME_PLAYER.PLAYER_UUID);
        public static final UniqueKey<GamePlayerGroupRecord> KEY_GAME_PLAYER_GROUP_PRIMARY = Internal.createUniqueKey(GamePlayerGroup.GAME_PLAYER_GROUP, "KEY_game_player_group_PRIMARY", GamePlayerGroup.GAME_PLAYER_GROUP.GAME_UUID, GamePlayerGroup.GAME_PLAYER_GROUP.PLAYER_GROUP_UUID);
        public static final UniqueKey<PlayerRecord> KEY_PLAYER_PRIMARY = Internal.createUniqueKey(Player.PLAYER, "KEY_player_PRIMARY", Player.PLAYER.PLAYER_UUID);
        public static final UniqueKey<PlayerRecord> KEY_PLAYER_EMAIL_ADDRESS = Internal.createUniqueKey(Player.PLAYER, "KEY_player_email_address", Player.PLAYER.EMAIL_ADDRESS);
        public static final UniqueKey<PlayerRecord> KEY_PLAYER_DISPLAY_NAME = Internal.createUniqueKey(Player.PLAYER, "KEY_player_display_name", Player.PLAYER.DISPLAY_NAME);
        public static final UniqueKey<PlayerGroupRecord> KEY_PLAYER_GROUP_PRIMARY = Internal.createUniqueKey(PlayerGroup.PLAYER_GROUP, "KEY_player_group_PRIMARY", PlayerGroup.PLAYER_GROUP.PLAYER_GROUP_UUID);
        public static final UniqueKey<PlayerScoreRecord> KEY_PLAYER_SCORE_PRIMARY = Internal.createUniqueKey(PlayerScore.PLAYER_SCORE, "KEY_player_score_PRIMARY", PlayerScore.PLAYER_SCORE.PLAYER_UUID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<GameRecord, PlayerRecord> GAME_PLAYER_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, Game.GAME, "game_player_fk", Game.GAME.WINNER_PLAYER_UUID);
        public static final ForeignKey<GamePlayerRecord, GameRecord> GAME_PLAYER_GAME_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_GAME_PRIMARY, GamePlayer.GAME_PLAYER, "game_player_game_fk", GamePlayer.GAME_PLAYER.GAME_UUID);
        public static final ForeignKey<GamePlayerRecord, PlayerRecord> GAME_PLAYER_PLAYER_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, GamePlayer.GAME_PLAYER, "game_player_player_fk", GamePlayer.GAME_PLAYER.PLAYER_UUID);
        public static final ForeignKey<GamePlayerGroupRecord, GameRecord> GAME_PLAYER_GROUP_GAME_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_GAME_PRIMARY, GamePlayerGroup.GAME_PLAYER_GROUP, "game_player_group_game_fk", GamePlayerGroup.GAME_PLAYER_GROUP.GAME_UUID);
        public static final ForeignKey<GamePlayerGroupRecord, PlayerGroupRecord> GAME_PLAYER_GROUP_PLAYER_GROUP_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_GROUP_PRIMARY, GamePlayerGroup.GAME_PLAYER_GROUP, "game_player_group_player_group_fk", GamePlayerGroup.GAME_PLAYER_GROUP.PLAYER_GROUP_UUID);
        public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER1_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, PlayerGroup.PLAYER_GROUP, "player_group_player1_fk", PlayerGroup.PLAYER_GROUP.PLAYER_UUID_1);
        public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER2_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, PlayerGroup.PLAYER_GROUP, "player_group_player2_fk", PlayerGroup.PLAYER_GROUP.PLAYER_UUID_2);
        public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER3_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, PlayerGroup.PLAYER_GROUP, "player_group_player3_fk", PlayerGroup.PLAYER_GROUP.PLAYER_UUID_3);
        public static final ForeignKey<PlayerGroupRecord, PlayerRecord> PLAYER_GROUP_PLAYER4_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, PlayerGroup.PLAYER_GROUP, "player_group_player4_fk", PlayerGroup.PLAYER_GROUP.PLAYER_UUID_4);
        public static final ForeignKey<PlayerScoreRecord, PlayerRecord> PLAYER_SCORE_PLAYER_FK = Internal.createForeignKey(com.gmo.big2.store.mysql.schema.jooq.Keys.KEY_PLAYER_PRIMARY, PlayerScore.PLAYER_SCORE, "player_score_player_fk", PlayerScore.PLAYER_SCORE.PLAYER_UUID);
    }
}
