/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq;


import com.gmo.big2.store.mysql.schema.jooq.tables.Game;
import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayer;
import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayerGroup;
import com.gmo.big2.store.mysql.schema.jooq.tables.Player;
import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerGroup;
import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerScore;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in big_two
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>big_two.game</code>.
     */
    public static final Game GAME = com.gmo.big2.store.mysql.schema.jooq.tables.Game.GAME;

    /**
     * The table <code>big_two.game_player</code>.
     */
    public static final GamePlayer GAME_PLAYER = com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayer.GAME_PLAYER;

    /**
     * The table <code>big_two.game_player_group</code>.
     */
    public static final GamePlayerGroup GAME_PLAYER_GROUP = com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayerGroup.GAME_PLAYER_GROUP;

    /**
     * The table <code>big_two.player</code>.
     */
    public static final Player PLAYER = com.gmo.big2.store.mysql.schema.jooq.tables.Player.PLAYER;

    /**
     * The table <code>big_two.player_group</code>.
     */
    public static final PlayerGroup PLAYER_GROUP = com.gmo.big2.store.mysql.schema.jooq.tables.PlayerGroup.PLAYER_GROUP;

    /**
     * The table <code>big_two.player_score</code>.
     */
    public static final PlayerScore PLAYER_SCORE = com.gmo.big2.store.mysql.schema.jooq.tables.PlayerScore.PLAYER_SCORE;
}
