/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq.tables.records;


import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayerGroup;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Row2;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamePlayerGroupRecord extends UpdatableRecordImpl<GamePlayerGroupRecord> implements Record2<UUID, UUID> {

    private static final long serialVersionUID = 1431755223;

    /**
     * Setter for <code>big_two.game_player_group.game_uuid</code>.
     */
    public GamePlayerGroupRecord setGameUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game_player_group.game_uuid</code>.
     */
    public UUID getGameUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>big_two.game_player_group.player_group_uuid</code>.
     */
    public GamePlayerGroupRecord setPlayerGroupUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game_player_group.player_group_uuid</code>.
     */
    public UUID getPlayerGroupUuid() {
        return (UUID) get(1);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record2 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UUID, UUID> fieldsRow() {
        return (Row2) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row2<UUID, UUID> valuesRow() {
        return (Row2) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return GamePlayerGroup.GAME_PLAYER_GROUP.GAME_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return GamePlayerGroup.GAME_PLAYER_GROUP.PLAYER_GROUP_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGameUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getPlayerGroupUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGameUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPlayerGroupUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerGroupRecord value1(UUID value) {
        setGameUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerGroupRecord value2(UUID value) {
        setPlayerGroupUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerGroupRecord values(UUID value1, UUID value2) {
        value1(value1);
        value2(value2);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamePlayerGroupRecord
     */
    public GamePlayerGroupRecord() {
        super(GamePlayerGroup.GAME_PLAYER_GROUP);
    }

    /**
     * Create a detached, initialised GamePlayerGroupRecord
     */
    public GamePlayerGroupRecord(UUID gameUuid, UUID playerGroupUuid) {
        super(GamePlayerGroup.GAME_PLAYER_GROUP);

        set(0, gameUuid);
        set(1, playerGroupUuid);
    }
}
