/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq.tables.records;


import com.gmo.big2.store.mysql.schema.jooq.tables.Game;

import java.time.Instant;
import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GameRecord extends UpdatableRecordImpl<GameRecord> implements Record3<UUID, String, Instant> {

    private static final long serialVersionUID = 10467734;

    /**
     * Setter for <code>big_two.game.game_uuid</code>.
     */
    public GameRecord setGameUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game.game_uuid</code>.
     */
    public UUID getGameUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>big_two.game.serialized_game</code>.
     */
    public GameRecord setSerializedGame(String value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game.serialized_game</code>.
     */
    public String getSerializedGame() {
        return (String) get(1);
    }

    /**
     * Setter for <code>big_two.game.game_completed_epoch_ms</code>.
     */
    public GameRecord setGameCompletedEpochMs(Instant value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game.game_completed_epoch_ms</code>.
     */
    public Instant getGameCompletedEpochMs() {
        return (Instant) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, String, Instant> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, String, Instant> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return Game.GAME.GAME_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Game.GAME.SERIALIZED_GAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Instant> field3() {
        return Game.GAME.GAME_COMPLETED_EPOCH_MS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGameUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getSerializedGame();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Instant component3() {
        return getGameCompletedEpochMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGameUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getSerializedGame();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Instant value3() {
        return getGameCompletedEpochMs();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameRecord value1(UUID value) {
        setGameUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameRecord value2(String value) {
        setSerializedGame(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameRecord value3(Instant value) {
        setGameCompletedEpochMs(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GameRecord values(UUID value1, String value2, Instant value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GameRecord
     */
    public GameRecord() {
        super(Game.GAME);
    }

    /**
     * Create a detached, initialised GameRecord
     */
    public GameRecord(UUID gameUuid, String serializedGame, Instant gameCompletedEpochMs) {
        super(Game.GAME);

        set(0, gameUuid);
        set(1, serializedGame);
        set(2, gameCompletedEpochMs);
    }
}
