/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq.tables.records;


import com.gmo.big2.store.mysql.schema.jooq.tables.GamePlayer;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record3;
import org.jooq.Row3;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GamePlayerRecord extends UpdatableRecordImpl<GamePlayerRecord> implements Record3<UUID, UUID, Integer> {

    private static final long serialVersionUID = 2129236854;

    /**
     * Setter for <code>big_two.game_player.game_uuid</code>.
     */
    public GamePlayerRecord setGameUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game_player.game_uuid</code>.
     */
    public UUID getGameUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>big_two.game_player.player_uuid</code>.
     */
    public GamePlayerRecord setPlayerUuid(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game_player.player_uuid</code>.
     */
    public UUID getPlayerUuid() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>big_two.game_player.score</code>.
     */
    public GamePlayerRecord setScore(Integer value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>big_two.game_player.score</code>.
     */
    public Integer getScore() {
        return (Integer) get(2);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<UUID, UUID> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record3 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, UUID, Integer> fieldsRow() {
        return (Row3) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row3<UUID, UUID, Integer> valuesRow() {
        return (Row3) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return GamePlayer.GAME_PLAYER.GAME_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return GamePlayer.GAME_PLAYER.PLAYER_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field3() {
        return GamePlayer.GAME_PLAYER.SCORE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getGameUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getPlayerUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getGameUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPlayerUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value3() {
        return getScore();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerRecord value1(UUID value) {
        setGameUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerRecord value2(UUID value) {
        setPlayerUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerRecord value3(Integer value) {
        setScore(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GamePlayerRecord values(UUID value1, UUID value2, Integer value3) {
        value1(value1);
        value2(value2);
        value3(value3);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GamePlayerRecord
     */
    public GamePlayerRecord() {
        super(GamePlayer.GAME_PLAYER);
    }

    /**
     * Create a detached, initialised GamePlayerRecord
     */
    public GamePlayerRecord(UUID gameUuid, UUID playerUuid, Integer score) {
        super(GamePlayer.GAME_PLAYER);

        set(0, gameUuid);
        set(1, playerUuid);
        set(2, score);
    }
}
