/*
 * This file is generated by jOOQ.
*/
package com.gmo.big2.store.mysql.schema.jooq.tables.records;


import com.gmo.big2.store.mysql.schema.jooq.tables.PlayerGroup;

import java.util.UUID;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerGroupRecord extends UpdatableRecordImpl<PlayerGroupRecord> implements Record5<UUID, UUID, UUID, UUID, UUID> {

    private static final long serialVersionUID = -1072244560;

    /**
     * Setter for <code>big_two.player_group.player_group_uuid</code>.
     */
    public PlayerGroupRecord setPlayerGroupUuid(UUID value) {
        set(0, value);
        return this;
    }

    /**
     * Getter for <code>big_two.player_group.player_group_uuid</code>.
     */
    public UUID getPlayerGroupUuid() {
        return (UUID) get(0);
    }

    /**
     * Setter for <code>big_two.player_group.player_uuid_1</code>.
     */
    public PlayerGroupRecord setPlayerUuid_1(UUID value) {
        set(1, value);
        return this;
    }

    /**
     * Getter for <code>big_two.player_group.player_uuid_1</code>.
     */
    public UUID getPlayerUuid_1() {
        return (UUID) get(1);
    }

    /**
     * Setter for <code>big_two.player_group.player_uuid_2</code>.
     */
    public PlayerGroupRecord setPlayerUuid_2(UUID value) {
        set(2, value);
        return this;
    }

    /**
     * Getter for <code>big_two.player_group.player_uuid_2</code>.
     */
    public UUID getPlayerUuid_2() {
        return (UUID) get(2);
    }

    /**
     * Setter for <code>big_two.player_group.player_uuid_3</code>.
     */
    public PlayerGroupRecord setPlayerUuid_3(UUID value) {
        set(3, value);
        return this;
    }

    /**
     * Getter for <code>big_two.player_group.player_uuid_3</code>.
     */
    public UUID getPlayerUuid_3() {
        return (UUID) get(3);
    }

    /**
     * Setter for <code>big_two.player_group.player_uuid_4</code>.
     */
    public PlayerGroupRecord setPlayerUuid_4(UUID value) {
        set(4, value);
        return this;
    }

    /**
     * Getter for <code>big_two.player_group.player_uuid_4</code>.
     */
    public UUID getPlayerUuid_4() {
        return (UUID) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<UUID> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, UUID, UUID, UUID, UUID> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<UUID, UUID, UUID, UUID, UUID> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field1() {
        return PlayerGroup.PLAYER_GROUP.PLAYER_GROUP_UUID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field2() {
        return PlayerGroup.PLAYER_GROUP.PLAYER_UUID_1;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field3() {
        return PlayerGroup.PLAYER_GROUP.PLAYER_UUID_2;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field4() {
        return PlayerGroup.PLAYER_GROUP.PLAYER_UUID_3;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<UUID> field5() {
        return PlayerGroup.PLAYER_GROUP.PLAYER_UUID_4;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component1() {
        return getPlayerGroupUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component2() {
        return getPlayerUuid_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component3() {
        return getPlayerUuid_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component4() {
        return getPlayerUuid_3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID component5() {
        return getPlayerUuid_4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value1() {
        return getPlayerGroupUuid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value2() {
        return getPlayerUuid_1();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value3() {
        return getPlayerUuid_2();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value4() {
        return getPlayerUuid_3();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UUID value5() {
        return getPlayerUuid_4();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroupRecord value1(UUID value) {
        setPlayerGroupUuid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroupRecord value2(UUID value) {
        setPlayerUuid_1(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroupRecord value3(UUID value) {
        setPlayerUuid_2(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroupRecord value4(UUID value) {
        setPlayerUuid_3(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroupRecord value5(UUID value) {
        setPlayerUuid_4(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public PlayerGroupRecord values(UUID value1, UUID value2, UUID value3, UUID value4, UUID value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PlayerGroupRecord
     */
    public PlayerGroupRecord() {
        super(PlayerGroup.PLAYER_GROUP);
    }

    /**
     * Create a detached, initialised PlayerGroupRecord
     */
    public PlayerGroupRecord(UUID playerGroupUuid, UUID playerUuid_1, UUID playerUuid_2, UUID playerUuid_3, UUID playerUuid_4) {
        super(PlayerGroup.PLAYER_GROUP);

        set(0, playerGroupUuid);
        set(1, playerUuid_1);
        set(2, playerUuid_2);
        set(3, playerUuid_3);
        set(4, playerUuid_4);
    }
}
